std_msgs/Header header
uint16 GPSWeek
float32 GPSTime
float32 AngRateRawX
float32 AngRateRawY
float32 AngRateRawZ
float32 AccelRawX
float32 AccelRawY
float32 AccelRawZ
uint8 States
uint8 GPSNumStasUsed
uint8 StatelliteStatus
uint8 GPSNumStas2Used
float32 GPSAge
uint8 GPSNumStas
uint8 GPSNumStas2
float32 PosLat
float32 PosLon
float32 PosAlt
float32 PosESigma
float32 PosNSigma
float32 PosUSigma
float32 VelE
float32 VelN
float32 VelU
float32 Vel
float32 VelESigma
float32 VelNSigma
float32 VelUSigma
float32 VelSigma
float32 AccelX
float32 AccelY
float32 AccelZ
float32 AngleHeading
float32 AnglePitch
float32 AngleRoll
float32 AngleHeadingSigma
float32 AnglePitchSigma
float32 AngleRollSigma
float32 AngRateX
float32 AngRateY
float32 AngRateZ





